QuarterlySales/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using QuarterlySales.Models;

namespace QuarterlySales.Controllers
{
    public class EmployeeController : Controller
    {
        private Repository<Employee> data { get; set; }
        public EmployeeController(SalesContext ctx) => data = new Repository<Employee>(ctx);

        public IActionResult Index() => RedirectToAction("Index", "Home");

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Employees = data.List(new QueryOptions<Employee> { OrderBy = e => e.Firstname });
            return View();
        }

        [HttpPost]
        public IActionResult Add(Employee employee)
        {
            // server side checks for remote validation
            string msg = Validate.CheckEmployee(data, employee);
            if (!string.IsNullOrEmpty(msg)) { 
                ModelState.AddModelError(nameof(Employee.DOB), msg);
            }
            msg = Validate.CheckManagerEmployeeMatch(data, employee);
            if (!string.IsNullOrEmpty(msg)) { 
                ModelState.AddModelError(nameof(Employee.ManagerId), msg);
            }

            if (ModelState.IsValid) {
                data.Insert(employee);
                data.Save();
                TempData["message"] = $"Employee {employee.Fullname} added";
                return RedirectToAction("Index", "Home");
            }
            else {
                ViewBag.Employees = data.List(new QueryOptions<Employee> { OrderBy = e => e.Firstname });
                return View();
            }
        }
    }
}

QuarterlySales/Controllers/SalesController.cs
using Microsoft.AspNetCore.Mvc;
using QuarterlySales.Models;

namespace QuarterlySales.Controllers
{
    public class SalesController : Controller
    {
        private UnitOfWork data { get; set; }
        public SalesController(SalesContext ctx) => data = new UnitOfWork(ctx);

        public IActionResult Index() => RedirectToAction("Index", "Home");

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Employees = data.Employees.List(new QueryOptions<Employee> { OrderBy = e => e.Firstname });
            return View();
        }

        [HttpPost]
        public IActionResult Add(Sales sales)
        {
            // server side check for remote validation
            string msg = Validate.CheckSales(data, sales);
            if (!string.IsNullOrEmpty(msg)) { 
                ModelState.AddModelError(nameof(sales.EmployeeId), msg);
            }

            if (ModelState.IsValid)
            {
                data.Sales.Insert(sales);
                data.Save();
                TempData["message"] = "Sales added";
                return RedirectToAction("Index", "Home");
            }
            else 
            {
                ViewBag.Employees = data.Employees.List(new QueryOptions<Employee> { OrderBy = e => e.Firstname });
                return View();
            }
            
        }
    }
}

QuarterlySales/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QuarterlySales.Models;
using QuarterlySales.Models.DomainModels;

namespace QuarterlySales.Controllers
{
    public class UsersController : Controller
    {
        private readonly SalesContext _context;

        public UsersController(SalesContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

       
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("username,password,isAdmin")] User user)
        {
            if (ModelState.IsValid)
            {
                user.isAdmin = false;
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }
            return View(user);
        }

        public IActionResult Login()
        {
            return View("Login");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(IFormCollection data)
        {
            String username = data["username"];
            String password = data["password"];

            var loggedUser = await _context.Users
                .FirstOrDefaultAsync(m => m.username == username && m.password == password);
            if (loggedUser != null)
            {
                HttpContext.Session.SetObject("user", loggedUser);
                return RedirectToAction("Index", "Home");
            }
            ViewBag.message = "Invalid login credentials";
            return View("Login");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> AddToAdmin(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            user.isAdmin = true;
            _context.Users.Update(user);
            await _context.SaveChangesAsync();
            if (user == null)
            {
                return NotFound();
            }
            return View(nameof(Index), await _context.Users.ToListAsync());
        }

        public async Task<IActionResult> RemoveFromAdmin(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            user.isAdmin = false;
            _context.Users.Update(user);
            await _context.SaveChangesAsync();
            if (user == null)
            {
                return NotFound();
            }
            return View(nameof(Index), await _context.Users.ToListAsync());
        }



        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.username == id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            if (user == null)
            {
                return NotFound();
            }

            return View(nameof(Index), await _context.Users.ToListAsync());
        }


        private bool UserExists(string id)
        {
            return _context.Users.Any(e => e.username == id);
        }
    }
}

QuarterlySales/Views/Shared/_Layout.cshtml
@using QuarterlySales.Models.DomainModels;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        @* based on default navbar that comes with MVC template *@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @{
                        var user = Context.Session.GetObject<User>("user");

                    }
                    <ul class="navbar-nav flex-grow-1 float-left">
                        @if (user == null)
                        {
                            <li class="nav-item">
                                @* go to action method that clears route segments and then loads home page *@
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="Create">Register</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item"><a  class="nav-link text-dark">Welcome @user.username!</a></li>
                            @if (user.isAdmin)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">Manage Users</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="Logout">Log Out</a>
                            </li>
                        }

                    </ul>
                    <ul class="navbar-nav flex-grow-1 float-right">
                        <li class="nav-item">
                            @* go to action method that clears route segments and then loads home page *@
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Clear">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Sales" asp-action="Add">Add Sales</a>
                        </li>
                        @if (user!=null && user.isAdmin)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Employee" asp-action="Add">Add Employee</a>
                            </li>
                        }
                        </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData.Keys.Contains("message"))
            {
                <h2 class="bg-light text-center p-2 mb-2">@TempData["message"]</h2>
            }
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>